version: '3'
services:
  hexo:
#    restart: always
    build:
      context: .
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_EMAIL: ${GITHUB_EMAIL}
    image: hexo-site:github_pages
    container_name: docker-github-pages
    environment: 
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_EMAIL=${GITHUB_EMAIL}
      - GITHUB_REPO=${GITHUB_REPO}
      - HEXO_THEME_NAME=${HEXO_THEME_NAME}
      - HEXO_THEME_REPO=${HEXO_THEME_REPO}
    ports:
      - "4000:4000"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $PWD/hexo-site/.deploy_git:/hexo/.deploy_git
      - $PWD/hexo-site/scaffolds:/hexo/scaffolds
      - $PWD/hexo-site/source:/hexo/source
      - $PWD/hexo-site/themes:/hexo/themes
      - $PWD/hexo-site/_config.yml:/hexo/_config.yml
      - $PWD/hexo-site/package.json:/hexo/package.json
      - $PWD/hexo-site/pnpm-lock.yaml:/hexo/pnpm-lock.yaml
#    entrypoint:
#     - sh
#      - /entrypoint.sh
    stdin_open: true
    tty: true
networks:
  default:
