version: '3'
services:
  docker-hexo:
    build: .
    container_name: docker-github-pages
    ports: 
      - "4000:4000"
    environment: 
      - HEXO_REPO=docker-github-pages
    volumes:
      - ./${HEXO_REPO}:/${HEXO_REPO}:rw

    entrypoint:
      - sh
      - /build_and_run.sh
networks:
  default:
