version: '3'
services:
  hexo:
    build: .
    container_name: docker-github-pages
    ports: 
      - "4000:4000"
    environment: 
      - HEXO_REPO=hexo-site
    volumes:
      - ./hexo-site:/hexo-site:rw

    entrypoint:
      - sh
      - /build_and_run.sh
networks:
  default:
