version: '3'
services:
  docker-github-pages:
    build: .
    ports: 
      - "4000:4000"
    environment: 
      - PUBLIC_HEXO_GITHUB_URL=https://github.com/peyoot/docker-github-pages.git
    entrypoint:
      - sh
      - /build_and_run.sh
