version: '3'
services:
  docker-hexo:
    build: .
    container_name: docker-github-pages
    ports: 
      - "4000:4000"
    environment: 
      - HEXO_REPO=docker-github-pages
    volumes:
      - ./docker-github-pages:/docker-github-pages:rw

    entrypoint:
      - sh
      - /build_and_run.sh
networks:
  default:
